# Generated by Django 4.2.23 on 2025-07-03 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_informationsystem_organization_systemcontrolstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancecontrol',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ControlMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapped_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapped_mappings', to='compliance.compliancecontrol')),
                ('source_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mappings', to='compliance.compliancecontrol')),
            ],
        ),
    ]
