# Generated by Django 4.2.23 on 2025-07-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_compliancecontrol_recommendation_controlmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationsystem',
            name='frameworks',
            field=models.ManyToManyField(blank=True, related_name='information_systems', to='compliance.complianceframework'),
        ),
        migrations.AlterField(
            model_name='informationsystem',
            name='compliance_controls',
            field=models.ManyToManyField(related_name='information_systems', through='compliance.SystemControlStatus', to='compliance.compliancecontrol'),
        ),
        migrations.AlterField(
            model_name='informationsystem',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='controlmapping',
            unique_together={('source_control', 'mapped_control')},
        ),
    ]
