# Generated by Django 4.2.23 on 2025-07-08 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0004_informationsystem_frameworks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RenameField(
            model_name='informationsystem',
            old_name='progress',
            new_name='cached_progress',
        ),
        migrations.AlterUniqueTogether(
            name='systemcontrolstatus',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='control',
        ),
        migrations.AddField(
            model_name='controlcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='compliance.controlcategory'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='evidence',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.evidence'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidence',
            name='reviewer_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='system_control_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='compliance.systemcontrolstatus'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='informationsystem',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems', to='compliance.organization'),
        ),
        migrations.AddField(
            model_name='systemcontrolstatus',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemcontrolstatus',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemcontrolstatus',
            name='controller_notes',
            field=models.TextField(blank=True, help_text='Notes from the controller'),
        ),
        migrations.AddField(
            model_name='systemcontrolstatus',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemcontrolstatus',
            name='evidence_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemcontrolstatus',
            name='evidence_upload_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemcontrolstatus',
            name='evidence_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemcontrolstatus',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance.complianceframework'),
        ),
        migrations.AddField(
            model_name='systemcontrolstatus',
            name='implementation_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('pending_evidence', 'Pending Evidence'), ('under_review', 'Under Review'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='systemcontrolstatus',
            name='previously_implemented',
            field=models.BooleanField(blank=True, help_text='Has this control been implemented before?', null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidence_type',
            field=models.CharField(choices=[('document', 'Document'), ('screenshot', 'Screenshot'), ('policy', 'Policy'), ('procedure', 'Procedure'), ('log', 'System Log'), ('certificate', 'Certificate'), ('configuration', 'Configuration File'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file_path',
            field=models.FileField(upload_to='evidence/'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemcontrolstatus',
            name='status',
            field=models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('partially_compliant', 'Partially Compliant'), ('not_applicable', 'Not Applicable'), ('under_review', 'Under Review')], default='under_review', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='systemcontrolstatus',
            unique_together={('system', 'framework', 'control')},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('deadline_approaching', 'Deadline Approaching'), ('deadline_passed', 'Deadline Passed'), ('evidence_uploaded', 'Evidence Uploaded'), ('evidence_approved', 'Evidence Approved'), ('evidence_rejected', 'Evidence Rejected'), ('control_assigned', 'Control Assigned')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system_control_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance.systemcontrolstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], max_length=20)),
                ('feedback', models.TextField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='compliance.evidence')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ControllerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100)),
                ('expertise_areas', models.TextField(blank=True, help_text='Areas of expertise (comma-separated)')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='systemcontrolstatus',
            name='controller',
            field=models.ForeignKey(blank=True, help_text='Controller assigned to implement this control', null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.controllerprofile'),
        ),
    ]
