# Generated by Django 4.2.23 on 2025-07-09 05:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0005_alter_evidence_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComplianceControl',
            new_name='Control',
        ),
        migrations.RenameModel(
            old_name='ComplianceFramework',
            new_name='Framework',
        ),
    ]
