# Generated by Django 4.2.23 on 2025-07-11 22:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_rename_compliancecontrol_control_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlcategory',
            options={'ordering': ['framework', 'code'], 'verbose_name_plural': 'Control Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='controlmapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='controlcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='controlmapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='controlmapping',
            name='target_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_mappings', to='compliance.control'),
        ),
        migrations.AddField(
            model_name='controlmapping',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='controlmapping',
            unique_together={('source_control', 'target_control')},
        ),
        migrations.RemoveField(
            model_name='controlmapping',
            name='mapped_control',
        ),
    ]
