# Generated by Django 4.2.23 on 2025-07-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_add_timestamps_to_controlcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
