# Generated by Django 4.2.23 on 2025-07-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_evidence_reviewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('deadline_approaching', 'Deadline Approaching'), ('deadline_passed', 'Deadline Passed'), ('deadline_warning', 'Deadline Warning'), ('deadline_overdue', 'Deadline Overdue'), ('evidence_uploaded', 'Evidence Uploaded'), ('evidence_approved', 'Evidence Approved'), ('evidence_rejected', 'Evidence Rejected'), ('control_assigned', 'Control Assigned'), ('email_sent', 'Email Alert Sent')], max_length=30),
        ),
    ]
