# Generated by Django 4.2.23 on 2025-07-28 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0009_alter_notification_options_notification_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique identifier from ngrok questionnaire', max_length=100, unique=True)),
                ('overall_score', models.IntegerField(help_text='Overall compliance score (0-100)')),
                ('maturity_level', models.CharField(choices=[('initial', 'Initial (1)'), ('developing', 'Developing (2)'), ('defined', 'Defined (3)'), ('managed', 'Managed (4)'), ('optimized', 'Optimized (5)')], max_length=20)),
                ('risk_level', models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('category_scores', models.JSONField(default=dict, help_text='Scores by category from questionnaire')),
                ('framework_recommendations', models.JSONField(default=list, help_text='Recommended frameworks')),
                ('gap_analysis', models.JSONField(default=dict, help_text='Gap analysis results')),
                ('priority_actions', models.JSONField(default=list, help_text='Priority actions to take')),
                ('raw_responses', models.JSONField(default=dict, help_text='Complete questionnaire responses')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
