# Generated by Django 4.2.23 on 2025-08-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0010_questionnaireresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='control',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
